version: '3.4'

services:
  app:
    build:
      target: fpm-dev
    volumes:
      - ../..:/var/www/app

  web:
    build:
      context: ../..
      target: nginx-dev
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ../..:/var/www/app