version: '3.4'

# Start app using production image and production config. (This does not support hot-reload of code changes)
# use `docker-compose up -d` to use prod image.
services:
  app:
    build:
      context: ../..
      args:
        SERVER_NAME: ${SERVER_NAME}
        COMPOSER_AUTH: ${COMPOSER_AUTH}
##    Pass environment variables either here or in .env.<prod|dev|test> in project root
#    environment:
#      DATABASE_URL: ${DATABASE_URL}
#      APP_ENV: <prod|test|dev>

  web:
    build:
      context: ../..
      args:
        SERVER_NAME: ${SERVER_NAME}
        COMPOSER_AUTH: ${COMPOSER_AUTH}
