version: '3.4'

services:
  app:
    build:
      target: fpm-prod
    restart: unless-stopped


  web:
    build:
      context: ../..
      target: nginx-prod
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

  cron:
    build:
      context: ../..
      target: cron-prod
      args:
        SERVER_NAME: ${SERVER_NAME}
        COMPOSER_AUTH: ${COMPOSER_AUTH}
    restart: unless-stopped


  supervisor:
    build:
      context: ../..
      target: supervisor-prod
      args:
        SERVER_NAME: ${SERVER_NAME}
        COMPOSER_AUTH: ${COMPOSER_AUTH}
    restart: unless-stopped